@startuml
title Overview
actor Player #white
participant GameSetupClient #lightblue
participant GameClient #lightblue
database LoginServer
database MatchMakingServer
database GameServer

Player -> GameSetupClient : Start
GameSetupClient -> Player : Ask for login
Player -> GameSetupClient : Input login details
GameSetupClient -> LoginServer : Try to login with credentials
LoginServer --> GameSetupClient : Login response
group login failed
GameSetupClient -> Player : Show error message
end group
GameSetupClient -> LoginServer : Request user data
LoginServer --> GameSetupClient : User Data
GameSetupClient -> GameSetupClient : Publish user data to UI\n(Ships, Weapons etc.)
group
Player -> GameSetupClient : Play
GameSetupClient -> Player : Choose game type\n(PvE, PvP etc.)
Player -> GameSetupClient : Select game type
GameSetupClient -> Player : Show more detailed game type\noptions (Mission, Map, PvP -type)
Player -> GameSetupClient : Select detailed options
GameSetupClient -> MatchMakingServer : Find game
group matchmaking server connection failure
MatchMakingServer --> GameSetupClient : Connection failure
GameSetupClient -> Player : Show error
end group
MatchMakingServer --> GameSetupClient : Game found
GameSetupClient -> GameSetupClient : Publish game data to UI
Player -> GameSetupClient : Accept game
GameSetupClient -> GameSetupClient : Present pre-game selections\n(Ship frame etc.)
Player -> GameSetupClient : Make pre-game selections.
Player -> GameSetupClient : Accept selections (ready)
GameSetupClient -> GameClient : Start with game session data
GameClient -> GameServer : Join game
GameServer --> GameClient : Join game response
GameServer -> GameClient : Start game
Player -> GameClient : Play game session
group gameserver connection failure
GameServer --> GameClient : Connection failure
GameClient -> GameClient : Show error
GameClient -> GameServer : Reconnect
end group
group gameclient crash or exit
GameClient -> GameClient : Crash or exit
GameSetupClient -> GameSetupClient : Show "rejoin/abandon" game
group rejoin
Player -> GameSetupClient : Rejoin
GameSetupClient -> GameClient : Restart
GameClient -> GameServer : Rejoin game
GameServer --> GameClient
end group
group abandon game
Player -> GameSetupClient : Abandon
GameSetupClient -> MatchMakingServer : Abandon game
MatchMakingServer -> MatchMakingServer : Free slot for someone else\nif possible.
MatchMakingServer --> GameSetupClient : Game abandoned
GameSetupClient -> GameSetupClient : Go back to mainscreen
end group
end group
GameServer -> GameClient : Game ends
GameClient -> GameClient : Show game end result\n(victory, defeat)
Player -> GameClient : Confirm game end result
GameClient -> GameSetupClient : Game finished
GameClient -> GameClient : Exit
GameSetupClient -> GameSetupClient : Show detailed game stats
Player -> GameSetupClient : Leave game
@enduml
